apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas:  4
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
      - name: todo-app-frontend
        image: nginx:stable-alpine3.23
        ports:
        - containerPort:  80
        resources:
          requests:
            cpu:  200m
            memory:  128Mi
          limits:
            cpu:  500m
            memory:  300Mi
